// Real browser workflow, isolated storage, synthetic data and blocked network.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const vm=require('node:vm');
const {chromium}=require('/Users/marcos/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const fixtureSource=fs.readFileSync(path.join(__dirname,'cost-mean-visual.cjs'),'utf8');
const ctx={};vm.runInNewContext(fixtureSource.slice(fixtureSource.indexOf('const quoteTime ='),fixtureSource.indexOf('(async () =>'))+'\nthis.fixtures=fixtures;',ctx);
const fixtures=JSON.parse(JSON.stringify(ctx.fixtures));
fixtures.crypto=[{id:'sol',positionId:'pos_crypto_sol',assetType:'crypto',sym:'SOL',name:'Solana',wallet:'Binance',custody:'exchange',qty:1,buy:100,openCost:100,avgBuy:100,date:'2026-01-01',cur:80,quoteCurrency:'USD',priceSource:'Synthetic',priceSourceTimestamp:new Date().toISOString(),status:'active'}];
fixtures.liquidity=[];fixtures.liquidityFx=[];fixtures.schemaVersion='position-v3';
let checks=0;const check=(condition,message)=>{assert(condition,message);checks++;};
(async()=>{
  const server=http.createServer((req,res)=>{if(req.url!=='/'){res.writeHead(204);res.end();return;}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(html);});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const origin=`http://127.0.0.1:${server.address().port}`;let browser;
  try{
    browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
    const context=await browser.newContext({viewport:{width:1440,height:1000}});
    await context.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());
    const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.goto(origin);await page.evaluate(f=>{ST={...ST,...f};renderAll();LANG='es';applyLang();showTab('liquidity');},fixtures);
    const preserved=await page.evaluate(()=>JSON.stringify([ST.otros,ST.cedearExpenses,ST.cedearValuations,ST.snaps,ST.aSnaps]));
    await page.locator('#tab-liquidity .btn-add').click();
    await page.locator('#liqEntity').fill('Binance');await page.locator('#liqBalance').fill('1000');
    await page.locator('#liquidityOverlay .btn-save').click();
    check(await page.locator('#liquidityTb tr').count()===1,'Initial balance visible');
    const id=await page.evaluate(()=>ST.liquidity[0].liquidityId);
    await page.evaluate(()=>{showTab('crypto');openPositionOperation('crypto','pos_crypto_sol','COMPRA');});
    check(await page.locator('#positionOperationLiquidity').inputValue()===id,'Matching custodian and currency preselected');
    await page.locator('#positionOperationQty').fill('2');await page.locator('#positionOperationPrice').fill('90');await page.locator('#positionOperationCommission').fill('1');
    check(await page.locator('#positionOperationLiquidityAmount').inputValue()==='181','Known cash effect auto-calculated');
    await page.locator('#positionOperationSave').click();
    check(await page.evaluate(()=>ST.liquidity[0].balanceDecimal==='819'&&ST.crypto[0].qty===3&&ST.crypto[0].openCost===281&&ST.crypto[0].buy===100),'BUY updates both states preserving original price');
    check(await page.evaluate(()=>ST.hist.filter(h=>h.type==='COMPRA').length===1&&ST.hist[0].liquidityId===ST.liquidity[0].liquidityId),'BUY has one linked history entry');
    await page.evaluate(()=>openPositionOperation('crypto','pos_crypto_sol','VENTA'));
    await page.locator('#positionOperationQty').fill('1');await page.locator('#positionOperationPrice').fill('100');await page.locator('#positionOperationCommission').fill('1');
    check(await page.locator('#positionOperationLiquidityAmount').inputValue()==='99','SELL auto-calculates net cash');
    await page.locator('#positionOperationSave').click();
    check(await page.evaluate(()=>ST.liquidity[0].balanceDecimal==='918'&&ST.crypto[0].qty===2),'SELL credits available cash');
    await page.evaluate(()=>openPositionOperation('crypto','pos_crypto_sol','COMPRA'));
    await page.locator('#positionOperationLiquidity').selectOption('');
    await page.locator('#positionOperationQty').fill('1');await page.locator('#positionOperationPrice').fill('80');await page.locator('#positionOperationCommission').fill('0');
    check(await page.locator('#positionOperationLiquidity').inputValue()==='','Explicit Sin afectar survives input edits');
    await page.locator('#positionOperationSave').click();
    check(await page.evaluate(()=>ST.liquidity[0].balanceDecimal==='918'&&ST.crypto[0].qty===3),'Outside funding leaves cash unchanged');
    await page.evaluate(()=>{showTab('liquidity');openLiquidityAccount();});
    await page.locator('#liqEntity').fill('Banco');await page.locator('#liqCurrency').fill('EUR');await page.locator('#liqBalance').fill('200');
    await page.locator('#liquidityOverlay .btn-save').click();
    check(await page.locator('#liquidityTb').textContent().then(t=>t.includes('N/D')),'Missing conversion visible as N/D');
    await page.evaluate(()=>openLiquidityFx());await page.locator('#liqFxRate').fill('1.10');await page.locator('#liqFxSource').fill('Fuente sintética');
    const localTime=new Date(Date.now()-60000);const dateString=new Date(localTime.getTime()-localTime.getTimezoneOffset()*60000).toISOString().slice(0,16);
    await page.locator('#liqFxTime').fill(dateString);await page.locator('#liquidityOverlay .btn-save').click();
    check(await page.evaluate(()=>liquiditySummary().available.value===1138),'FX conversion uses saved source and timestamp');
    await page.evaluate(()=>showTab('dash'));
    check(await page.locator('#dashLiquidityTotals .liquidity-total').count()===5,'Dashboard has five distinct wealth/liquidity figures');
    check(await page.evaluate(()=>$('dHeroTotal').textContent===fmt(financialSummary().totalUSD)),'Hero includes available liquidity once');
    await page.waitForTimeout(350);await page.screenshot({path:'/private/tmp/mrp-liquidity-dashboard-desktop.png',fullPage:true});
    await page.evaluate(()=>showTab('hist'));await page.locator('#historyScope').selectOption('liquidity');
    check(await page.locator('#hTb').textContent().then(t=>t.includes('SALDO_INICIAL')&&t.includes('Liquidez:')),'History shows cash and linked trades');
    await page.evaluate(()=>showTab('crypto'));
    await page.locator('#cS').fill('BTC');await page.locator('#cN').fill('Bitcoin');await page.locator('#cQ').fill('1');await page.locator('#cP').fill('100');await page.locator('#cComm').fill('0');await page.locator('#cW').fill('Binance');
    check(await page.locator('#cLiquidity').inputValue()===id,'Initial buy funding simplified');
    await page.evaluate(()=>addAsset('crypto'));
    check(await page.evaluate(()=>ST.liquidity[0].balanceDecimal==='818'&&ST.crypto.some(a=>a.sym==='BTC')),'Initial buy also debits cash');
    check(await page.evaluate(()=>JSON.stringify([ST.otros,ST.cedearExpenses,ST.cedearValuations,ST.snaps,ST.aSnaps]))===preserved,'Existing CEDEAR lots, history and snapshots preserved');
    await page.evaluate(()=>{createLiquidityAccount({custodian:'Allaria',currency:'USD',balanceDecimal:'1000',availability:'immediate',assetKind:'fiat',date:'2026-01-01'});renderAll();showTab('otros');showOtrosTab('cedeares');openPositionOperation('cedeaar',consolidateCedears()[0].positionId,'VENTA');});
    const cedCash=await page.evaluate(()=>ST.liquidity.find(a=>a.custodian==='Allaria').liquidityId);
    check(await page.locator('#positionOperationLiquidity').inputValue()===cedCash,'CEDEAR uses its own broker cash');
    await page.locator('#positionOperationQty').fill('2');await page.locator('#positionOperationPrice').fill('100');await page.locator('#positionOperationCommission').fill('1');await page.locator('#positionOperationCurrency').selectOption('USD_MEP');
    await page.locator('#positionOperationSave').click();
    check(await page.evaluate(()=>ST.liquidity.find(a=>a.custodian==='Allaria').balanceDecimal==='1199'&&ST.cedearSales.length===1),'CEDEAR sale credits native proceeds and preserves lot allocations');
    await page.locator('#cedSym').fill('AAPL');await page.locator('#cedName').fill('Apple');await page.locator('#cedQty').fill('1');await page.locator('#cedRatio').fill('10');await page.locator('#cedUnitPrice').fill('10');await page.locator('#cedTotalCost').fill('11');await page.locator('#cedBroker').fill('Allaria');
    await page.locator('#cedCurrency').selectOption('USD_MEP');
    const lotCount=await page.evaluate(()=>ST.otros.length);
    await page.evaluate(()=>addOtro('cedeaar'));
    check(await page.evaluate(n=>ST.otros.length===n+1&&ST.liquidity.find(a=>a.custodian==='Allaria').balanceDecimal==='1188',lotCount),'New CEDEAR lot debits its own cash once');
    check(await page.evaluate(preserved=>JSON.stringify([ST.otros.slice(1),ST.cedearExpenses,ST.cedearValuations,ST.snaps,ST.aSnaps])===preserved,preserved),'Existing lot records and historical snapshots unchanged by CEDEAR trade');
    await page.evaluate(()=>showTab('liquidity'));await page.waitForTimeout(350);await page.screenshot({path:'/private/tmp/mrp-liquidity-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Liquidity mobile has no page overflow');
    await page.waitForTimeout(350);await page.screenshot({path:'/private/tmp/mrp-liquidity-mobile.png',fullPage:true});
    await page.locator('#tab-liquidity .btn-add').click();
    check(await page.locator('#liqEntity').isVisible()&&await page.locator('#liquidityOverlay .btn-save').isVisible(),'Mobile modal is usable');
    await page.waitForTimeout(350);await page.screenshot({path:'/private/tmp/mrp-liquidity-modal-mobile.png',fullPage:true});
    await page.locator('#liquidityOverlay .btn-cancel').click();await page.evaluate(()=>showTab('dash'));
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Dashboard mobile has no page overflow');
    await page.waitForTimeout(350);await page.screenshot({path:'/private/tmp/mrp-liquidity-dashboard-mobile.png',fullPage:true});
    await page.evaluate(()=>{ST.liquidity[0].custodian='<img src=x onerror="window.liquidityXss=1">';renderLiquidity();renderHist();});
    check(await page.locator('#liquidityTb img,#liquidityHistoryTb img,#hTb img').count()===0,'Untrusted names safely rendered');
    check(await page.evaluate(()=>window.liquidityXss)===undefined,'No injected scripts');
    assert.deepEqual(errors,[]);console.log(`OK Liquidez UI: ${checks} comprobaciones desktop/móvil; sin red externa.`);
  }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;});
