// Synthetic ledger checks. No account, credentials or network access.
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const harness=fs.readFileSync(path.join(__dirname,'regression.cjs'),'utf8').split('const tests = String.raw`')[0];
const outer={require,__dirname,console,URL,AbortController};
vm.runInNewContext(harness+'\nthis.context=context;this.app=appSource.slice(0,initIndex);',outer);
vm.runInContext(outer.app+String.raw`
let checks=0,syncs=0;
const check=(condition,message)=>{assert(condition,message);checks++;};
const base=JSON.parse(JSON.stringify(ST));
renderAll=()=>{};scheduleCloudSync=()=>syncs++;
const reset=()=>{ST=JSON.parse(JSON.stringify(base));syncs=0;};
const initial=(custodian,currency,balance,availability='immediate',assetKind='fiat')=>createLiquidityAccount({custodian,currency,balanceDecimal:balance,availability,assetKind,date:'2026-01-01'});
reset();ST.hist=[{id:'old',sym:'USD',type:'COMPRA',qty:9999,price:1,date:'2025-01-01',legacy:true}];
const legacy=JSON.stringify(ST.hist),preserved=JSON.stringify([ST.otros,ST.cedearExpenses,ST.cedearValuations,ST.snaps,ST.aSnaps]);
const cash=initial('Broker','USD','1000');
check(cash.balanceDecimal==='1000','No reconstruction from old history');
check(JSON.stringify(ST.hist.slice(1))===legacy,'Legacy history unchanged');
check(JSON.stringify([ST.otros,ST.cedearExpenses,ST.cedearValuations,ST.snaps,ST.aSnaps])===preserved,'CEDEAR and snapshots unchanged');
assert.throws(()=>initial('Broker','USD','100'),/ya existe/);checks++;
const eur=initial('Bank','EUR','100');
check(liquidityAccountValuation(eur).currentUSD===null,'EUR has no invented FX');
check(financialSummary().pending===1,'Missing FX is reported');
ST.liquidityFx=[{currency:'EUR',rateUSDDecimal:'1.1',source:'Synthetic quote',valuedAt:new Date().toISOString()}];
check(liquidityAccountValuation(eur).currentUSD===110,'Original EUR valued using documented FX');
ST.liquidityFx[0].valuedAt='2020-01-01T00:00:00Z';
check(liquidityAccountValuation(eur).currentUSD===null,'Stale conversion is pending');
const usd2=initial('Broker 2','USD','0');
const beforeTotal=liquiditySummary().available.value;
applyLiquidityMovement({liquidityId:cash.liquidityId,toLiquidityId:usd2.liquidityId,type:'TRANSFERENCIA',amountDecimal:'12.34567891',date:'2026-01-02'});
check(cash.balanceDecimal==='987.65432109'&&usd2.balanceDecimal==='12.34567891','Exact original-currency transfer');
check(liquiditySummary().available.value===beforeTotal,'Transfer preserves total wealth');
check(ST.hist[0].realizedPnl===null,'No transfer P/L');
const beforeBad=JSON.stringify(ST);
assert.throws(()=>commitLiquidityMutation(()=>applyLiquidityMovement({liquidityId:cash.liquidityId,type:'RETIRO',amountDecimal:'99999',date:'2026-01-02'})),/insuficiente/);checks++;
check(JSON.stringify(ST)===beforeBad,'Invalid movement rolls back whole state');
assert.throws(()=>applyLiquidityMovement({liquidityId:cash.liquidityId,toLiquidityId:eur.liquidityId,type:'TRANSFERENCIA',amountDecimal:'5',date:'2026-01-02'}),/real recibido/);checks++;
applyLiquidityMovement({liquidityId:cash.liquidityId,toLiquidityId:eur.liquidityId,type:'TRANSFERENCIA',amountDecimal:'5',destinationAmountDecimal:'4.5',feeDecimal:'0.1',date:'2026-01-02'});
check(eur.balanceDecimal==='104.5','Cross-currency transfer uses actual received amount');
const remunerated=initial('Flexible','USD','50','remunerated'),locked=initial('Locked','USD','500','invested','investment');
check(Math.abs(liquiditySummary().available.value-1044.9)<1e-8,'Available = immediate plus flexible only');
check(portfolioSummary().totalUSD===500,'Locked money counts as invested, once');
check(Math.abs(financialSummary().totalUSD-1544.9)<1e-8,'Wealth = invested + available, not all balances twice');
assert.throws(()=>initial('Risk','USD','10','immediate','investment'),/disponibilidad/);checks++;
const fund=findLiquidity(cash.liquidityId);
const asset={id:'asset',positionId:'pos_crypto_asset',assetType:'crypto',sym:'BTC',name:'BTC',wallet:'Broker',qty:1,buy:100,openCost:100,avgBuy:100,cur:120,date:'2025-01-01',status:'active'};ST.crypto=[asset];
const tradeBefore=fund.balanceDecimal,count=ST.hist.length;
commitLiquidityMutation(()=>{applyPositionOperation(findPosition(asset.positionId,'crypto'),'crypto','COMPRA',{qty:2,price:100,comm:2,feeStatus:'recorded',date:'2026-01-02'});applyLiquidityFunding(ST.hist[0],{liquidityId:fund.liquidityId,amountDecimal:'202'});});
check(findLiquidity(fund.liquidityId).balanceDecimal===decSub(tradeBefore,'202'),'BUY debits cash including fee');
check(ST.crypto[0].qty===3&&ST.crypto[0].openCost===302&&ST.crypto[0].buy===100,'BUY updates weighted cost, original price preserved');
check(ST.hist.length===count+1&&ST.hist[0].liquidityId===fund.liquidityId,'Only one historical record for linked BUY');
commitLiquidityMutation(()=>{applyPositionOperation(ST.crypto[0],'crypto','VENTA',{qty:1,price:150,comm:1,feeStatus:'recorded',date:'2026-01-03'});applyLiquidityFunding(ST.hist[0],{liquidityId:fund.liquidityId,amountDecimal:'149'});});
check(findLiquidity(fund.liquidityId).balanceDecimal===decSub(tradeBefore,'53'),'SELL credits actual net proceeds');
check(ST.crypto[0].qty===2&&Math.abs(ST.crypto[0].openCost-201.33333333333331)<1e-8,'SELL removes weighted open cost');
const outside=findLiquidity(fund.liquidityId).balanceDecimal;
commitLiquidityMutation(()=>{applyPositionOperation(ST.crypto[0],'crypto','COMPRA',{qty:1,price:90,comm:0,feeStatus:'confirmed_zero',date:'2026-01-04'});applyLiquidityFunding(ST.hist[0],{});});
check(findLiquidity(fund.liquidityId).balanceDecimal===outside,'Sin afectar Liquidez does not alter balances');
assert.throws(()=>commitLiquidityMutation(()=>{applyPositionOperation(ST.crypto[0],'crypto','COMPRA',{qty:1,price:100,comm:0,feeStatus:'confirmed_zero',date:'2026-01-04'});applyLiquidityFunding(ST.hist[0],{liquidityId:locked.liquidityId,amountDecimal:'100'});}),/disponible/);checks++;
assert.throws(()=>commitLiquidityMutation(()=>{applyPositionOperation(ST.crypto[0],'crypto','COMPRA',{qty:1,price:100,comm:0,feeStatus:'confirmed_zero',date:'2026-01-04'});applyLiquidityFunding(ST.hist[0],{liquidityId:fund.liquidityId,amountDecimal:'99'});}),/coincidir/);checks++;
assert.throws(()=>commitLiquidityMutation(()=>{applyPositionOperation(ST.crypto[0],'crypto','VENTA',{qty:100,price:150,comm:0,date:'2026-01-04'});}),/más de/);checks++;
const stable={id:'stable',positionId:'pos_crypto_stable',assetType:'crypto',sym:'USDT',name:'Tether',wallet:'Exchange',qty:1000,buy:0.98,openCost:980,avgBuy:0.98,cur:0.999,quoteCurrency:'USD',priceSource:'Synthetic quote',priceSourceTimestamp:new Date().toISOString(),date:'2025-01-01',status:'active'};
ST.crypto.push(stable);const totalBefore=financialSummary().totalUSD;
assert.throws(()=>initial('Exchange','USDT','1000','immediate','stablecoin'),/duplicarlo/);checks++;
let stableId;
commitLiquidityMutation(()=>{stableId=reclassifyCryptoToLiquidity(stable.positionId,{quantityDecimal:'400',date:'2026-01-04'}).liquidityId;});
check(ST.crypto.find(a=>a.id==='stable').qty===600&&findLiquidity(stableId).balanceDecimal==='400','Reclassification moves, does not duplicate units');
check(Math.abs(financialSummary().totalUSD-totalBefore)<1e-8,'Stable reclassification preserves total wealth');
check(findLiquidity(stableId).basisUSDDecimal==='392'&&ST.hist[0].realizedPnl===null,'Reclassification preserves cost without P/L');
commitLiquidityMutation(()=>reclassifyLiquidityToCrypto(stableId,{quantityDecimal:'400',date:'2026-01-04'}));
check(ST.crypto.find(a=>a.id==='stable').qty===1000&&ST.crypto.find(a=>a.id==='stable').openCost===980,'Round trip preserves quantity and historical cost');
check(ST.crypto.find(a=>a.id==='stable').positionId===stable.positionId,'Original positionId preserved');
const manual=initial('Wallet','USDC','20','immediate','stablecoin');
const newCrypto=reclassifyLiquidityToCrypto(manual.liquidityId,{quantityDecimal:'5',date:'2026-01-04'});
check(newCrypto.costUnknown&&directUSDValuation(newCrypto,'Cripto').costUSD===null&&calc(newCrypto).pnl===null,'Unknown cost is not fabricated');
check(positionAverage(newCrypto)===null&&calcDCA(newCrypto).totalInv===null,'DCA keeps unknown basis pending');
check(validatePortfolioStateShape(ST),'New state valid for backup and sync');
check(validatePortfolioStateShape(JSON.parse(JSON.stringify(sanitizePortfolioState(ST)))),'New decimals survive backup round trip');
assert.throws(()=>createLiquidityAccount({custodian:'Future',currency:'USD',balanceDecimal:'10',date:'2999-01-01'}),/fecha/);checks++;
assert.throws(()=>applyLiquidityMovement({liquidityId:fund.liquidityId,type:'APORTE',amountDecimal:'1',date:'2026-02-30'}),/válido/);checks++;
const tiny={id:'tiny',positionId:'pos_crypto_tiny',assetType:'crypto',sym:'USDD',name:'USDD',wallet:'Tiny',qty:1e-8,buy:1,openCost:1e-8,avgBuy:1,cur:1,quoteCurrency:'USD',priceSource:'Synthetic USD quote',priceSourceTimestamp:new Date().toISOString(),date:'2026-01-01',status:'active'};
ST.crypto.push(tiny);const tinyAccount=reclassifyCryptoToLiquidity(tiny.positionId,{quantityDecimal:'0.00000001',date:'2026-01-04'});
check(tinyAccount.balanceDecimal==='0.00000001'&&tinyAccount.basisUSDDecimal==='0.00000001','Tiny units and basis remain exact');
reclassifyLiquidityToCrypto(tinyAccount.liquidityId,{quantityDecimal:'0.00000001',date:'2026-01-04'});
check(ST.crypto.find(a=>a.id==='tiny').qty===1e-8&&ST.crypto.find(a=>a.id==='tiny').openCost===1e-8,'Tiny-unit round trip preserves original position');
const usdtQuoted={id:'usdtquoted',positionId:'pos_crypto_usdtquoted',assetType:'crypto',sym:'USDC',name:'USDC',wallet:'USDT quoted',qty:10,buy:1,openCost:10,avgBuy:1,cur:0.99,quoteCurrency:'USD',priceSource:'Binance · USDT',priceSourceTimestamp:new Date().toISOString(),date:'2026-01-01',status:'active'};
ST.crypto.push(usdtQuoted);const usdcCash=reclassifyCryptoToLiquidity(usdtQuoted.positionId,{quantityDecimal:'10',date:'2026-01-04'});
check(liquidityAccountValuation(usdcCash).currentUSD===null,'USDT quote is not silently assumed to be USD');
const rawBefore=JSON.stringify(ST);localStorage.setItem(SKEY,rawBefore);const write=localStorage.setItem;
localStorage.setItem=(key,value)=>{if(key===SKEY)throw new Error('Synthetic QuotaExceededError');write(key,value);};
const syncBefore=syncs;
assert.throws(()=>commitLiquidityMutation(()=>applyLiquidityMovement({liquidityId:fund.liquidityId,type:'APORTE',amountDecimal:'10',date:'2026-01-05'})),/revertida/);checks++;
check(JSON.stringify(ST)===rawBefore&&localStorage.getItem(SKEY)===rawBefore&&syncs===syncBefore,'Storage failure leaves memory, disk and cloud unchanged');
localStorage.setItem=write;
commitLiquidityMutation(()=>applyLiquidityMovement({liquidityId:fund.liquidityId,type:'APORTE',amountDecimal:'10',date:'2026-01-05'}));
check(localStorage.getItem(LIQUIDITY_BACKUP_KEY)!=null,'Pre-change local backup exists');
check(JSON.parse(localStorage.getItem(SKEY)).liquidity.some(a=>a.liquidityId===fund.liquidityId),'Successful commit persists both ledger and positions');
const timeBefore=localStorage.getItem('mrp_last_local_change'),timestampBefore=JSON.stringify(ST),timestampSync=syncs;
localStorage.setItem=(key,value)=>{if(key==='mrp_last_local_change')throw new Error('Synthetic timestamp quota');write(key,value);};
assert.throws(()=>commitLiquidityMutation(()=>applyLiquidityMovement({liquidityId:fund.liquidityId,type:'APORTE',amountDecimal:'10',date:'2026-01-05'})),/revertida/);checks++;
check(JSON.stringify(ST)===timestampBefore&&localStorage.getItem(SKEY)===timestampBefore&&localStorage.getItem('mrp_last_local_change')===timeBefore&&syncs===timestampSync,'Partial persistence failure restores full old state');
localStorage.setItem=write;
renderAll=()=>{throw new Error('Synthetic render failure');};
assert.throws(()=>commitLiquidityMutation(()=>applyLiquidityMovement({liquidityId:fund.liquidityId,type:'APORTE',amountDecimal:'1',date:'2026-01-05'})),error=>error.saved===true);checks++;
check(localStorage.getItem(SKEY)===JSON.stringify(ST)&&JSON.stringify(ST)!==timestampBefore,'Render failure never rolls back an already persisted operation');
renderAll=()=>{};
const invalid=JSON.parse(JSON.stringify(ST));invalid.liquidity[0].balanceDecimal='-1';check(!validatePortfolioStateShape(invalid),'Negative imported balance rejected');
invalid.liquidity[0].balanceDecimal='1';invalid.hist.push({liquidityId:'liq_missing'});check(!validatePortfolioStateShape(invalid),'Orphan liquidity references rejected');
console.log('OK Liquidez: '+checks+' comprobaciones; datos sintéticos, sin red.');
`,outer.context,{filename:'liquidity-checks.js'});
