// Synthetic review rules and persistence; no portfolio access or network.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const harness=fs.readFileSync(path.join(__dirname,'regression.cjs'),'utf8').split('const tests = String.raw`')[0];
const outer={require,__dirname,console,URL,AbortController};
vm.runInNewContext(harness+'\nthis.context=context;this.app=appSource.slice(0,initIndex);',outer);
vm.runInContext(outer.app+String.raw`
let checks=0,syncs=0;
const check=(condition,message)=>{assert(condition,message);checks++;};
const original=JSON.parse(JSON.stringify(ST));
check(profitReviewSettings({}).gainThresholdPct===30&&profitReviewSettings({}).concentrationThresholdPct===15,'Approved initial thresholds apply to existing V3 states without settings');
check(original.profitReview.gainThresholdPct===30&&original.profitReview.concentrationThresholdPct===15,'New states use approved 30 and 15 percent defaults');
check(profitReviewSettings({profitReview:{gainThresholdPct:45,concentrationThresholdPct:20}}).gainThresholdPct===45,'User settings override initial defaults');
const settings={...profitReviewSettings(),gainThresholdPct:50,concentrationThresholdPct:50};
const asset=(id,wallet,cur)=>({id,positionId:'pos_'+id,sym:'BTC',name:'Bitcoin',wallet,custody:'exchange',qty:10,buy:100,avgBuy:100,openCost:1000,status:'active',cur,quoteCurrency:'USD',priceStatus:'realtime',priceSource:'Synthetic',priceSourceTimestamp:new Date().toISOString(),date:'2026-01-01',costFeeStatus:'fees_recorded'});
const reset=()=>{ST=JSON.parse(JSON.stringify(original));ST.crypto=[asset('one','Binance',150),asset('two','Exodus',50)];ST.stocks=[];ST.otros=[];ST.hist=[];ST.liquidity=[];ST.profitReview={...profitReviewSettings(original),gainThresholdPct:null,concentrationThresholdPct:null};};
reset();const before=JSON.stringify(ST),metrics=JSON.stringify(portfolioSummary());
check(profitReviewData().rows.length===0,'Explicitly cleared thresholds remain disabled');
check(profitReviewData(portfolioSummary(),profitReviewSettings({})).rows[0].partial,'Approved initial thresholds produce review alerts from current data');
let data=profitReviewData(portfolioSummary(),settings),row=data.rows[0];
check(data.rows.length===1&&row.positionId==='pos_one','Custodians remain separate and losing position is excluded');
check(row.roi===50&&row.weight===75&&row.instrumentWeight===100,'ROI, position weight and consolidated exposure share valuations');
check(row.gainHit&&row.concentrationHit&&row.partial,'Equality at both thresholds activates two independent factors');
check(row.reasons.filter(reason=>reason==='Revisar toma parcial de beneficios').length===1,'Combined rule is not double counted');
check(profitReviewData(portfolioSummary(),{...settings,gainThresholdPct:50.001}).rows.length===0,'Concentration alone is not a profit-taking alert');
check(!profitReviewData(portfolioSummary(),{...settings,concentrationThresholdPct:75.001}).rows[0].partial,'A single gain factor is informational');
check(profitReviewData(portfolioSummary(),{...settings,partialEnabled:false}).rows[0].partial===false,'Partial review can be disabled');
check(JSON.stringify(ST)===before&&JSON.stringify(portfolioSummary())===metrics,'Review calculations never mutate holdings or metrics');
ST.stocks=[{...asset('stock','',150),sym:'AAPL',broker:'Broker',tg:150}];
check(profitReviewData().rows[0].targetHit,'Existing stock target works before gain thresholds are set');
check(profitReviewData(portfolioSummary(),{...settings,targetEnabled:false}).positions.find(r=>r.positionId==='pos_stock').targetHit===false,'Target switch is respected');
ST.stocks[0].tg=151;
check(!profitReviewData().positions.find(r=>r.positionId==='pos_stock').targetHit,'Price below target is not reached');
ST.stocks[0].tg=150;ST.stocks[0].quoteCurrency='EUR';
check(!profitReviewData().positions.find(r=>r.positionId==='pos_stock').targetHit,'No target comparison across currencies');
ST.stocks[0].quoteCurrency='USD';ST.stocks[0].costUnknown=true;
row=profitReviewData().rows[0];check(row.roi===null&&row.targetHit&&!row.partial,'Missing cost permits target only, not profit or partial review');
reset();ST.crypto[1].cur=null;
row=profitReviewData(portfolioSummary(),settings).rows[0];
check(row.gainHit&&!row.concentrationHit&&!row.weightReliable,'Incomplete denominator suppresses concentration only');
reset();ST.crypto[1].priceSourceTimestamp='2020-01-01T00:00:00Z';
check(!profitReviewData(portfolioSummary(),settings).weightReliable,'Old denominator also suppresses concentration');
ST.crypto[0].priceSourceTimestamp='2020-01-01T00:00:00Z';
check(profitReviewData(portfolioSummary(),settings).rows.length===0,'Old quotes generate no new review alerts');
reset();createLiquidityAccount({custodian:'Bank',currency:'USD',balanceDecimal:'10000',availability:'immediate',assetKind:'fiat',date:'2026-01-01'});
check(profitReviewData(portfolioSummary(),settings).rows[0].weight===75,'Available cash is excluded from invested-asset weight');
createLiquidityAccount({custodian:'Bank',currency:'USD',balanceDecimal:'1000',availability:'invested',assetKind:'investment',date:'2026-01-01',product:'Locked'});
check(profitReviewData(portfolioSummary(),settings).rows[0].weight===50,'Unavailable invested products remain in existing Risk denominator');
check(profitReviewData().positions.length===2,'Cash products do not become tradable position alerts');
reset();const cash=createLiquidityAccount({custodian:'Binance',currency:'USD',balanceDecimal:'0',availability:'immediate',assetKind:'fiat',date:'2026-01-01'});
applyPositionOperation(ST.crypto[0],'crypto','VENTA',{qty:2,price:150,comm:2,feeStatus:'recorded',date:'2026-01-02'});
applyLiquidityFunding(ST.hist[0],{liquidityId:cash.liquidityId,amountDecimal:'298'});
let sale=profitReviewLastSale('pos_one');
check(sale.remaining===80&&sale.realized===98,'Partial sale retains 80 percent and realizes net profit of 98');
check(sale.liquidityAmount==='298'&&sale.liquidityCurrency==='USD','Released liquidity includes returned principal and remains distinct from profit');
check(ST.crypto[0].openCost===800&&portfolioSummary().items.find(i=>i.sourceAsset.positionId==='pos_one').pnlUSD===400,'Remaining cost and unrealized P/L use the existing sale engine');
check(ST.hist.length===2&&ST.liquidity[0].balanceDecimal==='298','One sale entry and one cash credit');
ST.hist[0].qtyBefore=undefined;ST.hist[0].qtyAfter=undefined;
check(profitReviewLastSale('pos_one').remaining===null,'Legacy or CEDEAR sale without quantity snapshots is not reconstructed');
ST.hist[0].feeStatus='not_recorded';check(profitReviewLastSale('pos_one').realized===null,'Unknown commission does not produce a definite realized result');
check(profitReviewLastSale('missing')===null,'No invented past sale');
check(validatePortfolioStateShape({...ST,profitReview:settings}),'Settings accepted in existing state');
for(const invalid of [{gainThresholdPct:0},{concentrationThresholdPct:101},{gainThresholdPct:'50'},{targetEnabled:'true'},{unknown:1}])check(!validatePortfolioStateShape({...ST,profitReview:invalid}),'Invalid imported settings rejected');
const roundTrip=sanitizePortfolioState(JSON.parse(JSON.stringify({...ST,profitReview:settings})));
check(JSON.stringify(roundTrip.profitReview)===JSON.stringify(settings),'Settings preserved in backup round trip');
reset();renderAll=()=>{};renderProfitReview=()=>{};scheduleCloudSync=()=>syncs++;
const untouched=JSON.stringify([ST.crypto,ST.stocks,ST.otros,ST.hist,ST.snaps,ST.aSnaps]);
document.getElementById('profitGainThreshold').value='50';document.getElementById('profitWeightThreshold').value='50';
for(const id of ['profitGainEnabled','profitConcentrationEnabled','profitTargetEnabled','profitPartialEnabled'])document.getElementById(id).checked=true;
document.getElementById('profitReviewSettings').dataset={};
saveProfitReviewSettings();
check(ST.profitReview.gainThresholdPct===50&&JSON.parse(localStorage.getItem(SKEY)).profitReview.concentrationThresholdPct===50,'Only explicitly entered thresholds are persisted');
check(JSON.stringify([ST.crypto,ST.stocks,ST.otros,ST.hist,ST.snaps,ST.aSnaps])===untouched,'Saving settings leaves financial records unchanged');
const saved=JSON.stringify(ST),stored=localStorage.getItem(SKEY),syncBefore=syncs,originalSet=localStorage.setItem;
localStorage.setItem=(key,value)=>{if(key===SKEY)throw new Error('Synthetic quota');return originalSet(key,value);};
document.getElementById('profitGainThreshold').value='60';saveProfitReviewSettings();
check(JSON.stringify(ST)===saved&&localStorage.getItem(SKEY)===stored&&syncs===syncBefore,'Failed settings save restores memory and storage, with no upload');
localStorage.setItem=originalSet;
console.log('OK Gestión de beneficios: '+checks+' comprobaciones; sin datos reales ni red.');
`,outer.context);
